### ISSUE TITLE
Twitter 权限问题

### ISSUE THREAD

**Issue by symant233** [HiedaNaKan/NTTools#2]
为什么要那么多权限, 甚至还要访问私信...
![image](https://user-images.githubusercontent.com/25316350/56456490-cc4c1980-639f-11e9-9af9-462c7c961c4f.png)

**Comment by HiedaNaKan** [comment]
那窝改一下 (x

**Comment by HiedaNaKan** [comment]
现在是read only了 (

**Comment by symant233** [comment]
![image](https://user-images.githubusercontent.com/25316350/56844222-67347e80-68df-11e9-84e9-a73620dd24d9.png)
good

**Comment by HiedaNaKan** [comment]
因为新增了通过 Twitter个人数据 中的 tweet.js 和 like.js 删除推文和打心的功能，修改为 read/write (
